name: "[Workflow] Path to Live"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Create release"
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.zip.outputs.artifact }}
      branch_name: ${{ steps.semver_tag.outputs.branch }}
      semver_tag: ${{ steps.semver_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
            fetch-depth: "0"
      - name: "Zip descriptions"
        id: "zip"
        env:
          target: "job-descriptions.zip"
          source: "."
          include: '-i "*roles*"'
        run: |
          zip -vrX ${{ env.target }} ${{ env.source }} ${{ env.include }}
          echo "artifact=${{ env.target }}" >> $GITHUB_OUTPUT
      - name: Upload Zip artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: descriptions
          path: |
            ./${{ steps.zip.outputs.artifact }}
      - name: "Generate semver tag and release"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/actions/semver@b605e1e2c94b399e8139c4c2be2c8730700e0004
        with:
          create_release: true
          prerelease: ${{ github.ref != 'refs/heads/main' }}

  end:
    name: "Workflow summary"
    if: always()
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: "Git"
        run: |
          echo "### Git info" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| Branch | ${{ needs.release.outputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Semver tag | ${{ needs.release.outputs.semver_tag }} |"  >> $GITHUB_STEP_SUMMARY
      - name: "Release"
        run: |
          echo "### Release info" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| tag | ${{ needs.release.outputs.semver_tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| artifact | ${{ needs.release.outputs.artifact }} |"  >> $GITHUB_STEP_SUMMARY
